language: node_js

node_js:
    - "4"


install:
  - npm install -g codecov istanbul

script:
    - npm i eslint
    - node node_modules/eslint/bin/eslint "lib/ace/**/*.js"
    - istanbul cover lib/ace/test/all.js
    - codecov

matrix:
    fast_finish: false

cache:
    directories:
        - node_modules

sudo: false
